### ISSUE TITLE
Systemui crashes when Live Caption enabled 

### ISSUE THREAD

**Issue by ashoksoni** [PotatoProject/frameworks_base#3]
In aosp volume panel before your own volume panel implementation, systemui didn't crash and volume panel was able to show live caption option in volume panel but now it forces systemui to crash.

Here's the log.

time: 1597119042723
msg: android.content.res.Resources$NotFoundException: Resource ID #0x0
stacktrace: android.view.InflateException: Binary XML file line #18 in com.android.systemui:layout/volume_tool_tip_view: Resource ID #0x0
Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x0
	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:237)
	at android.content.res.Resources.getColor(Resources.java:982)
	at android.content.Context.getColor(Context.java:671)
	at androidx.core.content.ContextCompat.getColor(ContextCompat.java:514)
	at com.android.systemui.volume.VolumeToolTipView.drawArrow(VolumeToolTipView.java:69)
	at com.android.systemui.volume.VolumeToolTipView.onFinishInflate(VolumeToolTipView.java:58)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1136)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
	at android.view.ViewStub.inflateViewNoAdd(ViewStub.java:272)
	at android.view.ViewStub.inflate(ViewStub.java:305)
	at com.android.systemui.volume.VolumeDialogImpl.showCaptionsTooltip(VolumeDialogImpl.java:736)
	at com.android.systemui.volume.VolumeDialogImpl.updateODICaptionsH(VolumeDialogImpl.java:793)
	at com.android.systemui.volume.VolumeDialogImpl.access$4200(VolumeDialogImpl.java:128)
	at com.android.systemui.volume.VolumeDialogImpl$5.onCaptionComponentStateChanged(VolumeDialogImpl.java:1586)
	at com.android.systemui.volume.VolumeDialogControllerImpl$C.lambda$onCaptionComponentStateChanged$0(VolumeDialogControllerImpl.java:995)
	at com.android.systemui.volume.-$$Lambda$VolumeDialogControllerImpl$C$Q4oXmUMuqtOXvcXaIdydaXsm_80.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7398)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:929)

**Comment by ashoksoni** [comment]
It was a module issue. Closing this.
